### ISSUE TITLE
特殊目标 桌面的手势 对任务栏无效

### ISSUE THREAD

**Issue by zhangenming** [yingDev/WGestures2-mac-bugs#100]
不知道是有意还是无意
那是否可以考虑特殊目标里 新增一个 任务栏
毕竟任务栏常见  而桌面不常见

**Comment by superDMS** [comment]
任务栏是被那个底下边界触发给屏蔽了 ............即使禁用底部照样被屏蔽  应该改进

**Comment by yingDev** [comment]
你可以定义边缘上画的手势, 而不需要任务栏可见

**Comment by superDMS** [comment]
他的意思应该是说 在任务栏那使用正常手势 用不出来，那就是被底部的那个屏蔽了。 即使禁用了底部边缘手势也会照样屏蔽掉 正常手势。 这个逻辑其实可以优化一下。
