### ISSUE TITLE
建议: 1如圆圈所示  这个地方单独添加一个 添加目标的按钮 是否更好

### ISSUE THREAD

**Issue by zhangenming** [yingDev/WGestures2-mac-bugs#101]
![1639023576(1)](https://user-images.githubusercontent.com/21235555/145334264-195f20c9-514f-41f8-8853-52443adb1374.png)

2 此时chrome里手势是空的  但不能删除 删除的话上面group1里的也会被一起删除 非\~常\~难\~受\~

**Comment by yingDev** [comment]
不是这样工作的, 是先有这个应用程序, 然后才能把它加入分组. 分组中的条目则是对 应用程序的引用.

这种设计是有目的 的, 因为它允许你在 Google Chrome 上进一步覆盖 group 1 上的手势.

**Comment by zhangenming** [comment]
> 这种设计是有目的 的, 因为它允许你在 Google Chrome 上进一步覆盖 group 1 上的手势.

但我现在不需要进一步覆盖  本身是空的 却还占着地方 还不能删除 


没错 我理解的
可能是我的解释有问题
比如如图情况下的chrome

只有group1里有手势 自己单独是没有的 但下面还是有他的存在 是空的  这时候我想删除他就会把group也删除掉
应该可以理解成 我现在已经把chrome加到group1了 此时这俩应该不再互相关联(所以 如果圆圈里有这个加号会更直观)
这样  比如group1 里有chrome和edge  我设置了数个手势
然后我还有group2 里有Chrome和firfox 这三个应该是单独的
Chrome本身是空的  所以我应该能删除他才对  不然空的留在那里没意义呀  所以通过那个圆圈来给组里增加应用程序比通过下面的图标拖进去应该更直观
感谢

**Comment by yingDev** [comment]
> 这时候我想删除他就会把group也删除掉

你是想说 group 内该 app 的引用会被删掉对吧? group 本身应该不受影响才对.

的确, 空的 app 占用了一格, 不过,
- 大概率会有需要在 app 上重载手势的情况
- 如果你改变该 app 的路径/名称, 它们的引用都能同时更新
- 性能角度, 匹配手势的时候我们只需判断一次这个 app 以及所属 group,  而不是每个 group 下的每个 app 测试一次

最后, 其实初衷是, group =="接口", app =="类";  并非 group "拥有(has-a)" app, 而是 app "实现(is-a)" 几个 group (也就是加入它们). 因此 UI 上, group 后面不适合放个 "添加 app" 按钮. 

(我看你有 VSCode, 不知道是不是程序猿 :)

**Comment by zhangenming** [comment]
从代码开发层面可以理解
但用户体验是另一个不同的层面吧  最好不要混在一起
当然就事论事的话,  我说的这种形式也不一定用户体验更好
没关系 over  感谢
