### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by yuhangrao** [yingDev/WGestures2-mac-bugs#121]
希望更新可以直接调用下载链接下载，而不是打开网站自己点击下载。

**Comment by lhj5426** [comment]
借用你的帖子我也提一下
希望这个固定的悬浮菜单 可以 根据 前台的程序自动隐藏 显示 
举个例子 我给PS 和edge 都 设置了 固定菜单 并且都启动了固定 
我希望是 在我切换到PS的界面的时候 只显示PS的固定菜单 然后 窗口切换到了EDGE  只显示EDGE的固定菜单 
就是  希望 固定菜单 和窗口程序绑定 在哪个程序里就显示哪个 已经激活并且固定在屏幕上的菜单
 接着 楼上的操作 已经固定了PS 和EDGE的菜单 如果 切换到不是EDGE 或者PS的程序  不显示这2个菜单  只有在对应的程序里显示对应的 菜单 这样感觉更自由 一点要不 我没在浏览器里 我去摸鱼 聊QQ去了 这窗口上 还飞着 一个 固定菜单 有点突兀 您可以考虑下这个 设定么 开发者 老哥

**Comment by yingDev** [comment]
@yuhangrao  老实说，我是希望用户点进网站可以顺便看到将来的新产品.....

@lhj5426 在计划中，名曰“关联到窗口”，应该是会在 2.9 实现 ，实际涉及的问题略为复杂
