### ISSUE TITLE
细节问题

### ISSUE THREAD

**Issue by WZ-Tong** [yingDev/WGestures2-mac-bugs#130]
激活后激活码应不可复制，或复制为乱码
虽然是小众软件，但“没人能保证电脑一定是本人使用”

**Comment by yingDev** [comment]
win 版应该无法复制，你看到的可能是剪贴板之前的内容？
mac 版还没更新。

**Comment by yingDev** [comment]
win 版应该无法复制，你看到的可能是剪贴板之前的内容？
mac 版还没更新。
