### ISSUE TITLE
功能建议 手势识别超时

### ISSUE THREAD

**Issue by SheldonNico** [yingDev/WGestures2-mac-bugs#134]
一代可以设置超时自动取消手势（画到一半想取消）：即使已经识别了手势，但没有操作n秒后就退出手势模式执行正常操作。但2好像只能设置手势起始时的超时（或者这是bug？）

这个功能在一代还有个作用是，软件一旦识别手势过程中一直识别到按键就无法操作电脑了（比如鼠标右键已经松了，但wgesture还是识别的没有松，可能是软件问题，也可能是硬件问题，我遇到过几次非常抓狂），只能靠暂停wgesture的功能来退出，但我一般都忘了我的快捷键。有了这个功能就不用担心这种情况，比暂停快捷键直观且方便多了，如果有想要维持现在这种模式的就默认无限时长就好了，需要的再配置

![image](https://user-images.githubusercontent.com/11974052/147999934-9a537c3b-5df9-46f7-8b04-8a058a41cb18.png)

**Comment by yingDev** [comment]
实现倒不难。只是，多数人应该会选择胡乱画线来使轨迹失效。
所以，不确定这个选项是否值得添加（因为担心将来可能与新增功能冲突，需要慎重考虑）

**Comment by SheldonNico** [comment]
嗯 胡乱画线确实更直观
那就只用考虑第二个功能了，我才开始用二代，不知道会不会遇到一代的那种锁死，如果忘记暂停快捷键就职能重启解决的问题，如果遇到我提再提吧
