### ISSUE TITLE
教育邮箱优惠

### ISSUE THREAD

**Issue by Wulin-Tan** [yingDev/WGestures2-mac-bugs#141]
您好，请问教育邮箱如何发给您？支付宝和微信的备注留言都不能超过20字。
谢谢。

**Comment by yingDev** [comment]
可通过 edu 邮箱发送支付截图至 ***@***.***




YingDev
***@***.***




------------------ 原始邮件 ------------------
发件人: Wulin-Tan ***@***.***&gt;
发送时间: 2022年1月13日 00:14
收件人: yingDev/WGestures2-bugs ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yingDev/WGestures2-bugs] 教育邮箱优惠 (Issue #141)





 
您好，请问教育邮箱如何发给您？支付宝和微信的备注留言都不能超过20字。
 谢谢。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Wulin-Tan** [comment]
谢谢🙏
