### ISSUE TITLE
如何自定义鼠标侧键的功能？

### ISSUE THREAD

**Issue by fanyy0418** [yingDev/WGestures2-mac-bugs#231]
已经清空了默认配置，现在不知道怎么自定义鼠标侧键，因为电脑上有鼠标的驱动，所以无法正确感知到鼠标侧键。

**Comment by JohnKhanJr** [comment]
用鼠标厂商的专用程序来设置，如果没有，可以用XMouseButtonControl

**Comment by yingDev** [comment]
如果是罗技，需要在 option 里面把侧键设为默认（好像是）功能。然后 wg 就能识别了。&nbsp;




YingDev
***@***.***




------------------ 原始邮件 ------------------
发件人: JohnKhanJr ***@***.***&gt;
发送时间: 2023年5月2日 17:01
收件人: yingDev/WGestures2-bugs ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yingDev/WGestures2-bugs] 如何自定义鼠标侧键的功能？ (Issue #231)





 
用鼠标厂商的专用程序来设置，如果没有，可以用XMouseButtonControl

**Comment by fanyy0418** [comment]
> 

好的已经解决了。在罗技的驱动里，设置为默认的前进后退，就可以识别了。
