### ISSUE TITLE
2.9.1 版本 导致鼠标中键失效

### ISSUE THREAD

**Issue by SiaYung** [yingDev/WGestures2-mac-bugs#235]
如题

**Comment by yingDev** [comment]
具体指什么？
是不是其它件设置了中键功能，现在无法触发了？




YingDev
***@***.***




------------------ 原始邮件 ------------------
发件人: SiaYung ***@***.***&gt;
发送时间: 2023年5月4日 09:32
收件人: yingDev/WGestures2-bugs ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yingDev/WGestures2-bugs] 2.9.1 版本 导致鼠标中键失效 (Issue #235)





 
如题

**Comment by SiaYung** [comment]
其他软件只有一个 Listary 在桌面用中键调用菜单，其他的就没有了。

**Comment by SiaYung** [comment]
在 2.8.5 版本下，没有影响，中键点击任务栏图标打开程序、 Chrome 中键关闭标签页，中键打开收藏夹连接，这些功能在2.8.5 b版本下都是正常呢，升级至2.9.1后就不正常了。

**Comment by SiaYung** [comment]
又试了一下，上述功能， 需要按住Ctrl 再按 中键。

**Comment by yingDev** [comment]
如果360，退出后如何呢？




YingDev
***@***.***




------------------ 原始邮件 ------------------
发件人: zhj9709 ***@***.***&gt;
发送时间: 2023年5月4日 15:19
收件人: yingDev/WGestures2-bugs ***@***.***&gt;
抄送: 应元东 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [yingDev/WGestures2-bugs] 2.9.1 版本 导致鼠标中键失效 (Issue #235)





 
在 2.8.5 版本下，没有影响，中键点击任务栏图标打开程序、 Chrome 中键关闭标签页，中键打开收藏夹连接，这些功能在2.8.5 b版本下都是正常呢，升级至2.9.1后就不正常了。

**Comment by SiaYung** [comment]
没有u使用360 这些软件，安全软件只有火绒

**Comment by SiaYung** [comment]
找到问题了，是被 quicker 影响了

**Comment by SiaYung** [comment]
有時候正常，有時候又不正常，還是回退到 2.8.5 穩定了
