### ISSUE TITLE
屏幕边缘的滚轮不起作用

### ISSUE THREAD

**Issue by viocha** [yingDev/WGestures2-mac-bugs#285]
![image](https://github.com/yingDev/WGestures2-bugs/assets/66580331/10965d7f-8ab6-477d-87c8-0b06138a78f0)
屏幕边缘的横向滚轮无法录制，纵向滚轮可以录制但是无法响应

**Comment by eKnaiXgnaW** [comment]
屏幕底边缘+鼠标滑动--启用.

**Comment by viocha** [comment]
> 屏幕底边缘+鼠标滑动--启用.

已经启用了，如图所示

**Comment by viocha** [comment]
鼠标中键点击有效，但是滚动无效

**Comment by eKnaiXgnaW** [comment]
![image](https://github.com/yingDev/WGestures2-bugs/assets/71743409/92240d47-724f-4de5-a3cc-5c094f39e9c7)
图片中是滚轮启用了,那个鼠标滑动也要启用.

**Comment by viocha** [comment]
谢谢，已经解决了
