### ISSUE TITLE
WG2在使用预设{VOLUME_UP}{VOLUME_DOWN}调节音量时,会同时触发B和C键,引起不可预知的副作用

### ISSUE THREAD

**Issue by eKnaiXgnaW** [yingDev/WGestures2-mac-bugs#286]
PC网页版抖音,默认有一个快捷键列表,开启/关闭弹幕-B收藏/取消收藏-C,打开抖音时用手势调节音量,会自动收藏视频或者开关弹幕.
我用按键检测查看发现调节音量会触发BC按键,这个调节音量通过什么实现,有没有其他办法

**Comment by AssassinJY** [comment]
the same problem as you

**Comment by AssassinJY** [comment]
![image](https://github.com/user-attachments/assets/43450d9f-e714-4955-928c-b730bf15dd35)

我用 lua 脚本暂时规避了这个问题，唯一副作用就是响应时间比原生稍微慢了一些。

**Comment by eKnaiXgnaW** [comment]
> ![image](https://private-user-images.githubusercontent.com/16275411/356892862-43450d9f-e714-4955-928c-b730bf15dd35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDMwNDYsIm5iZiI6MTcyMzU0Mjc0NiwicGF0aCI6Ii8xNjI3NTQxMS8zNTY4OTI4NjItNDM0NTBkOWYtZTcxNC00OTU1LTkyOGMtYjczMGJmMTVkZDM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA5NTIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MGNhZjllMzVmNzk2YzE5ZWFlNzY1NDMwOGNjMjYyNGQ0YWEyODUzNTBhMTc3MjRlMWU3ZGUwN2E0MGE4YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W_SJhCMwIuQlONY2KPl3PYDyHBbP9LfU6Cd9cWt6S_0)
> 
> 我用 lua 脚本暂时规避了这个问题，唯一副作用就是响应时间比原生稍微慢了一些。

用Lua脚本和用按键是一种方式,本质一样.这个脚本的写法没有触发Bug是因为{VOLUME_UP}前面多了一个"^",就是按住Ctrl再按音量键,这样确实不会触发Bug了.
function wgAction()
  WG.Keys('{VOLUME_UP 2}')
end
比如这样写还是会触发.
受你的启发,我现在是在用原生按键的写法,碰到抖音就按住Shift或者Ctrl按滚轮,不会触发了.

**Comment by AssassinJY** [comment]
> > ![image](https://private-user-images.githubusercontent.com/16275411/356892862-43450d9f-e714-4955-928c-b730bf15dd35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDMwNDYsIm5iZiI6MTcyMzU0Mjc0NiwicGF0aCI6Ii8xNjI3NTQxMS8zNTY4OTI4NjItNDM0NTBkOWYtZTcxNC00OTU1LTkyOGMtYjczMGJmMTVkZDM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA5NTIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MGNhZjllMzVmNzk2YzE5ZWFlNzY1NDMwOGNjMjYyNGQ0YWEyODUzNTBhMTc3MjRlMWU3ZGUwN2E0MGE4YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W_SJhCMwIuQlONY2KPl3PYDyHBbP9LfU6Cd9cWt6S_0)
> > 我用 lua 脚本暂时规避了这个问题，唯一副作用就是响应时间比原生稍微慢了一些。
> 
> 用Lua脚本和用按键是一种方式,本质一样.这个脚本的写法没有触发Bug是因为{VOLUME_UP}前面多了一个"^",就是按住Ctrl再按音量键,这样确实不会触发Bug了. function wgAction() WG.Keys('{VOLUME_UP 2}') end 比如这样写还是会触发. 受你的启发,我现在是在用原生按键的写法,碰到抖音就按住Shift或者Ctrl按滚轮,不会触发了.

哈哈哈，我确实没发现多了个 ^，不过我也知道怎么改了

**Comment by eKnaiXgnaW** [comment]
嗯,歪打正着.要么直接把修饰按键写到按键上,要么遇到抖音就按住修饰键,暂时这样吧.
