### ISSUE TITLE
[Windows]屏幕上显示的手势名称也会被截断

### ISSUE THREAD

**Issue by JohnKhanJr** [yingDev/WGestures2-mac-bugs#42]
WGestures2 中的效果如图：![](https://s3.bmp.ovh/imgs/2021/10/bfa3d29e4463e540.png)

一代的效果如图：![](https://s3.bmp.ovh/imgs/2021/10/5448c30516108ef5.png)

**Comment by zhj9709** [comment]
9个汉字加三个点，我刚试了一下，确实是这样

**Comment by yingDev** [comment]
2.4.4 增加了长度
