### ISSUE TITLE
win L 没有反应

### ISSUE THREAD

**Issue by cclume** [yingDev/WGestures2-mac-bugs#46]
![image](https://user-images.githubusercontent.com/63960943/136902414-7e56b822-2ecd-4791-a08e-69cfaaf7caa4.png)

**Comment by cclume** [comment]
版本是最新的2.4.0

**Comment by yingDev** [comment]
系统保留了这个快捷键，代码也没有针对这个做特殊处理， 因此模拟输出无效。
可以用 cmd脚本：
```bat
rundll32.exe user32.dll,LockWorkStation
```
