### ISSUE TITLE
win版本如何导入1.8.4版本的手势? 

### ISSUE THREAD

**Issue by xung** [yingDev/WGestures2-mac-bugs#54]
1.8.4版本定义了很多手势, 如何导入到WGestures2呢?  二者的备份文件格式好像不同.

**Comment by JohnKhanJr** [comment]
作者说目前暂不支持导入旧版手势。只能对照着一个个添加了，具体方法见：[链接](https://github.com/yingDev/WGestures2-bugs/issues/33)

**Comment by xung** [comment]
好的,感谢.
