### ISSUE TITLE
[Windows] 2.5.0手势轨迹延迟

### ISSUE THREAD

**Issue by zhj9709** [yingDev/WGestures2-mac-bugs#55]
https://user-images.githubusercontent.com/13991774/137832417-8c8ffeb0-c87b-4c55-8deb-b232795c7141.mp4

**Comment by yingDev** [comment]
是 win11 么?

**Comment by zhj9709** [comment]
> 是 win11 么?

是的，这视频是不是加载不出来？

**Comment by yingDev** [comment]
好像所有视频都播放不了.
正常手势应该是这样流畅的:
https://raw.githubusercontent.com/yingDev/WGestures2-bugs/main/res/a.mp4

**Comment by yingDev** [comment]
目前反应的几个用户好像都是 win11. 你有测试过 win 10 设备么?

**Comment by zhj9709** [comment]
> 目前反应的几个用户好像都是 win11. 你有测试过 win 10 设备么?

视频重新上传了，你看一下，我两台电脑都是win11。我找找win10设备试试

**Comment by zhj9709** [comment]
> 目前反应的几个用户好像都是 win11. 你有测试过 win 10 设备么?

你网站上下载WGestures好慢，下次可以在github上上传一份吗

**Comment by zhj9709** [comment]
> 目前反应的几个用户好像都是 win11. 你有测试过 win 10 设备么?

刚拿我的win11笔记本试了一下，没有我视频中的问题

**Comment by yingDev** [comment]
这就奇怪了。&nbsp;
这两个设备差异在哪？核显 vs 独显？




YingDev
***@***.***




------------------ 原始邮件 ------------------
发件人: zhj9709 ***@***.***&gt;
发送时间: 2021年10月19日 10:28
收件人: yingDev/WGestures2-bugs ***@***.***&gt;
抄送: 应元东 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[yingDev/WGestures2-bugs] [Windows] 2.5.0手势轨迹延迟 (Issue #55)





  
目前反应的几个用户好像都是 win11. 你有测试过 win 10 设备么?
  
刚拿我的win11笔记本试了一下，没有我视频中的问题
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhj9709** [comment]
> 这就奇怪了。&nbsp; 这两个设备差异在哪？核显 vs 独显？ YingDev ***@***.***
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: zhj9709 ***@***.***&gt; 发送时间: 2021年10月19日 10:28 收件人: yingDev/WGestures2-bugs ***@***.***&gt; 抄送: 应元东 ***@***.***&gt;, Comment ***@***.***&gt; 主题: 回复：[yingDev/WGestures2-bugs] [Windows] 2.5.0手势轨迹延迟 (Issue #55) 目前反应的几个用户好像都是 win11. 你有测试过 win 10 设备么? 刚拿我的win11笔记本试了一下，没有我视频中的问题 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

都是核显，R5 4650G，R5 5600U。台式机等我晚上回去卸载重装或重启电脑试试

**Comment by luoshuaidev** [comment]
可能和鼠标有关, 我两个鼠标, 一个是送的三无产品鼠标, 用起来很正常, 触发很准确, 触发也能看到线条. 
但是换成雷蛇鼠标体验就大大下降了. 
误触发很多, 或者触发不了, 具体表现为: 
1. 拐弯的经常触发失败, 例如: "└" "┘" "┏" "┓"
2. ── 横向居然会触发 ↘
3. 看不到轨迹(我用的时候触发了就松手了, 雷蛇鼠标经常看不到轨迹, 还没出来, 我就松手了, 但是触发动作了)
这些问题在 WGesture 1 上没有遇到过. 

我用 WGesture 5, 6 年了, 不存在操作问题, 操作不到位的地方. 手势都形成了肌肉记忆. 
运行环境完全一直, 就是一台电脑插上两个鼠标. 

好像也不是鼠标DPI高, 或者轮询率高导致. 
DPI我在雷蛇的雷云里面调低了, 轮询率只能降低到500, 改了之后没有明显改善. 
工作良好的山寨三无产品鼠标 DPI 不超过1000, 轮询率未知.

**Comment by luoshuaidev** [comment]
@yingDev 而且我可以确定不是雷蛇鼠标有问题, 因为我有两只同样型号的鼠标(黑色/白色), 使用 WGesture2 是同样的情况. 

![1](https://user-images.githubusercontent.com/65377438/137888467-2f96b90a-4c58-429c-862c-08dd64e86ade.gif)
这是雷蛇鼠标, 经常触发失败, 而且看不到轨迹. 

![2](https://user-images.githubusercontent.com/65377438/137888629-60abedef-0deb-416a-a6f2-1686dc61266b.gif)
这是山寨三无鼠标, 工作良好. 

同样的手势, 雷蛇鼠标触发有问题, 另一款鼠标我故意倾斜, 小拐弯 都能触发. 很奇怪.

**Comment by yingDev** [comment]
> 
> 
> 可能和鼠标有关, 我两个鼠标, 一个是送的三无产品鼠标, 用起来很正常, 触发很准确, 触发也能看到线条. 但是换成雷蛇鼠标体验就大大下降了. 误触发很多, 或者触发不了, 具体表现为:
> 
>     1. 拐弯的经常触发失败, 例如: "└" "┘" "┏" "┓"
> 
>     2. ── 横向居然会触发 ↘
> 
>     3. 看不到轨迹(我用的时候触发了就松手了, 雷蛇鼠标经常看不到轨迹, 还没出来, 我就松手了, 但是触发动作了)
>        这些问题在 WGesture 1 上没有遇到过.
> 
> 
> 我用 WGesture 5, 6 年了, 不存在操作问题, 操作不到位的地方. 手势都形成了肌肉记忆. 运行环境完全一直, 就是一台电脑插上两个鼠标.
> 
> 好像也不是鼠标DPI高, 或者轮询率高导致. DPI我在雷蛇的雷云里面调低了, 轮询率只能降低到500, 改了之后没有明显改善. 工作良好的山寨三无产品鼠标 DPI 不超过1000, 轮询率未知.

2.4 是否存在这个问题?
2.5 增加了轨迹插值, 也就是系统卡顿的时候, 即使指针跳越, 轨迹依然是按照用户实际移动来计算.  
如此看来, 的确有可能是 dpi 过高, 产生了一些无效数据.

请问具体是哪一款鼠标, 我买一个试试

**Comment by luoshuaidev** [comment]
> > 可能和鼠标有关, 我两个鼠标, 一个是送的三无产品鼠标, 用起来很正常, 触发很准确, 触发也能看到线条. 但是换成雷蛇鼠标体验就大大下降了. 误触发很多, 或者触发不了, 具体表现为:
> > ```
> > 1. 拐弯的经常触发失败, 例如: "└" "┘" "┏" "┓"
> > 
> > 2. ── 横向居然会触发 ↘
> > 
> > 3. 看不到轨迹(我用的时候触发了就松手了, 雷蛇鼠标经常看不到轨迹, 还没出来, 我就松手了, 但是触发动作了)
> >    这些问题在 WGesture 1 上没有遇到过.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我用 WGesture 5, 6 年了, 不存在操作问题, 操作不到位的地方. 手势都形成了肌肉记忆. 运行环境完全一直, 就是一台电脑插上两个鼠标.
> > 好像也不是鼠标DPI高, 或者轮询率高导致. DPI我在雷蛇的雷云里面调低了, 轮询率只能降低到500, 改了之后没有明显改善. 工作良好的山寨三无产品鼠标 DPI 不超过1000, 轮询率未知.
> 
> 2.4 是否存在这个问题? 2.5 增加了轨迹插值, 也就是系统卡顿的时候, 即使指针跳越, 轨迹依然是按照用户实际移动来计算. 如此看来, 的确有可能是 dpi 过高, 产生了一些无效数据.
> 
> 请问具体是哪一款鼠标, 我买一个试试

2.4也存在这个问题, 
我从 2.3.5 到 2.5.0 都用过, 2.4.4用的时间最久, 前几个版本用的时间都不长, 出新版本就升级了. 
我昨天还尝试退回 2.3.5, 2.3.8, 2.4.0, 发现都存在这个问题. 

鼠标就是雷蛇蝰蛇标准版, 京东100左右的那个.

**Comment by luoshuaidev** [comment]
> > > 可能和鼠标有关, 我两个鼠标, 一个是送的三无产品鼠标, 用起来很正常, 触发很准确, 触发也能看到线条. 但是换成雷蛇鼠标体验就大大下降了. 误触发很多, 或者触发不了, 具体表现为:
> > > ```
> > > 1. 拐弯的经常触发失败, 例如: "└" "┘" "┏" "┓"
> > > 
> > > 2. ── 横向居然会触发 ↘
> > > 
> > > 3. 看不到轨迹(我用的时候触发了就松手了, 雷蛇鼠标经常看不到轨迹, 还没出来, 我就松手了, 但是触发动作了)
> > >    这些问题在 WGesture 1 上没有遇到过.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我用 WGesture 5, 6 年了, 不存在操作问题, 操作不到位的地方. 手势都形成了肌肉记忆. 运行环境完全一直, 就是一台电脑插上两个鼠标.
> > > 好像也不是鼠标DPI高, 或者轮询率高导致. DPI我在雷蛇的雷云里面调低了, 轮询率只能降低到500, 改了之后没有明显改善. 工作良好的山寨三无产品鼠标 DPI 不超过1000, 轮询率未知.
> > 
> > 
> > 2.4 是否存在这个问题? 2.5 增加了轨迹插值, 也就是系统卡顿的时候, 即使指针跳越, 轨迹依然是按照用户实际移动来计算. 如此看来, 的确有可能是 dpi 过高, 产生了一些无效数据.
> > 请问具体是哪一款鼠标, 我买一个试试
> 
> 2.4也存在这个问题, 我从 2.3.5 到 2.5.0 都用过, 2.4.4用的时间最久, 前几个版本用的时间都不长, 出新版本就升级了. 我昨天还尝试退回 2.3.5, 2.3.8, 2.4.0, 发现都存在这个问题.
> 
> 鼠标就是雷蛇蝰蛇标准版, 京东100左右的那个.

现在的环境是, Win10 21H1 19043.1288, WGesture 2.5.0
上面提到了显卡, 我的显卡CPU信息如下: 
CPU

	Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

	基准速度:	2.60 GHz
	插槽:	1
	内核:	6
	逻辑处理器:	12
	虚拟化:	已启用
	L1 缓存:	384 KB
	L2 缓存:	1.5 MB
	L3 缓存:	12.0 MB

	利用率	23%
	速度	3.51 GHz
	正常运行时间	1:19:06:25
	进程	442
	线程	7047
	句柄	233826


GPU 0

	Intel(R) UHD Graphics 630

	驱动程序版本:	27.20.100.8681
	驱动程序日期:	2020/9/5 星期六
	DirectX 版本:	12 (FL 12.1)
	物理位置：	PCI 总线 0、设备 2、功能 0

	利用率	0%
	专用 GPU 内存	
	共享 GPU 内存	0.0/15.9 GB
	GPU 内存	0.0/15.9 GB

GPU 1

	NVIDIA GeForce RTX 2060

	驱动程序版本:	27.21.14.6647
	驱动程序日期:	2021/5/13 星期四
	DirectX 版本:	12 (FL 12.1)
	物理位置：	PCI 总线 1、设备 0、功能 0

	利用率	0%
	专用 GPU 内存	3.4/6.0 GB
	共享 GPU 内存	0.2/15.9 GB
	GPU 内存	3.6/21.9 GB

**Comment by luoshuaidev** [comment]
> > > > 可能和鼠标有关, 我两个鼠标, 一个是送的三无产品鼠标, 用起来很正常, 触发很准确, 触发也能看到线条. 但是换成雷蛇鼠标体验就大大下降了. 误触发很多, 或者触发不了, 具体表现为:
> > > > ```
> > > > 1. 拐弯的经常触发失败, 例如: "└" "┘" "┏" "┓"
> > > > 
> > > > 2. ── 横向居然会触发 ↘
> > > > 
> > > > 3. 看不到轨迹(我用的时候触发了就松手了, 雷蛇鼠标经常看不到轨迹, 还没出来, 我就松手了, 但是触发动作了)
> > > >    这些问题在 WGesture 1 上没有遇到过.
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 我用 WGesture 5, 6 年了, 不存在操作问题, 操作不到位的地方. 手势都形成了肌肉记忆. 运行环境完全一直, 就是一台电脑插上两个鼠标.
> > > > 好像也不是鼠标DPI高, 或者轮询率高导致. DPI我在雷蛇的雷云里面调低了, 轮询率只能降低到500, 改了之后没有明显改善. 工作良好的山寨三无产品鼠标 DPI 不超过1000, 轮询率未知.
> > > 
> > > 
> > > 2.4 是否存在这个问题? 2.5 增加了轨迹插值, 也就是系统卡顿的时候, 即使指针跳越, 轨迹依然是按照用户实际移动来计算. 如此看来, 的确有可能是 dpi 过高, 产生了一些无效数据.
> > > 请问具体是哪一款鼠标, 我买一个试试
> > 
> > 
> > 2.4也存在这个问题, 我从 2.3.5 到 2.5.0 都用过, 2.4.4用的时间最久, 前几个版本用的时间都不长, 出新版本就升级了. 我昨天还尝试退回 2.3.5, 2.3.8, 2.4.0, 发现都存在这个问题.
> > 鼠标就是雷蛇蝰蛇标准版, 京东100左右的那个.
> 
> 现在的环境是, Win10 21H1 19043.1288, WGesture 2.5.0 上面提到了显卡, 我的显卡CPU信息如下: CPU
> 
> ```
> Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
> 
> 基准速度:	2.60 GHz
> 插槽:	1
> 内核:	6
> 逻辑处理器:	12
> 虚拟化:	已启用
> L1 缓存:	384 KB
> L2 缓存:	1.5 MB
> L3 缓存:	12.0 MB
> 
> 利用率	23%
> 速度	3.51 GHz
> 正常运行时间	1:19:06:25
> 进程	442
> 线程	7047
> 句柄	233826
> ```
> 
> GPU 0
> 
> ```
> Intel(R) UHD Graphics 630
> 
> 驱动程序版本:	27.20.100.8681
> 驱动程序日期:	2020/9/5 星期六
> DirectX 版本:	12 (FL 12.1)
> 物理位置：	PCI 总线 0、设备 2、功能 0
> 
> 利用率	0%
> 专用 GPU 内存	
> 共享 GPU 内存	0.0/15.9 GB
> GPU 内存	0.0/15.9 GB
> ```
> 
> GPU 1
> 
> ```
> NVIDIA GeForce RTX 2060
> 
> 驱动程序版本:	27.21.14.6647
> 驱动程序日期:	2021/5/13 星期四
> DirectX 版本:	12 (FL 12.1)
> 物理位置：	PCI 总线 1、设备 0、功能 0
> 
> 利用率	0%
> 专用 GPU 内存	3.4/6.0 GB
> 共享 GPU 内存	0.2/15.9 GB
> GPU 内存	3.6/21.9 GB
> ```

我顺便确认下和屏幕有没有关系, 现在是笔记本接了 4K 屏, 换用内置的 1080P 屏幕存在同样问题.

**Comment by yingDev** [comment]
@luoshuaidev 

试试重新录入那些默认的简单手势, 看是否能提高匹配度.

因为WG2 不再单纯匹配方向, 出于优化目的, 会比较两个手势点数量, 如果相差过大, 就认为不匹配. 某些鼠标可能 "精度过高" 以至于把任何抖动都传入系统了.

**Comment by zhj9709** [comment]
@yingDev 我视频中，台式机win11，鼠标罗技G102。我用笔记本试了，系统版本相同，鼠标试了另一个G102以及罗技G304都没问题，Win10上测试G102没问题。回报率都是1000，DPI都是2500左右。#51 可以优化一下吗，画个直角有时候都能在直角处拐个小弧线，虽然不影响使用，但影响观感。还有#37  我现在还没法把画的手势给截下来。

**Comment by yingDev** [comment]
> 
> 
> @yingDev 我视频中，台式机win11，鼠标罗技G102。我用笔记本试了，系统版本相同，鼠标试了另一个G102以及罗技G304都没问题，Win10上测试G102没问题。回报率都是1000，DPI都是2500左右。#51 可以优化一下吗，画个直角有时候都能在直角处拐个小弧线，虽然不影响使用，但影响观感。还有#37 我现在还没法把画的手势给截下来。

所以依然没有规律可循 ? :-(

- 直角变圆角是平滑效果. 我感觉轨迹就是方便确认自己没画错, 然后不能太粗糙. 为什么会有精确画线这种需求呢?
- 这个后面会加上判断, 如果当前手势没有可能的键盘修饰键, 就不拦截

**Comment by yingDev** [comment]
@luoshuaidev 
> 鼠标就是雷蛇蝰蛇标准版, 京东100左右的那个.

就是 DeathAdder 对么?
恰好我有一只, 然而并未出现问题. 用雷云配置各种参数也不影响.

啊啊啊....到底什么鬼

**Comment by luoshuaidev** [comment]
> @luoshuaidev
> 
> 试试重新录入那些默认的简单手势, 看是否能提高匹配度.
> 
> 因为WG2 不再单纯匹配方向, 出于优化目的, 会比较两个手势点数量, 如果相差过大, 就认为不匹配. 某些鼠标可能 "精度过高" 以至于把任何抖动都传入系统了.

MAC版和Windows版比较手势的方式是一样的吗? 
我刚刚试了一下, windows上有问题的鼠标, 在MAC版 BigSur 11.6 / WGesture 2.3.2 就没有任何问题. 正确触发率几乎100%, 
MAC版我设置的手势和Windows上是一模一样的. 

windows之前我用 WGesture 1 也是几乎100%正确触发.

**Comment by luoshuaidev** [comment]
> > @luoshuaidev
> > 试试重新录入那些默认的简单手势, 看是否能提高匹配度.
> > 因为WG2 不再单纯匹配方向, 出于优化目的, 会比较两个手势点数量, 如果相差过大, 就认为不匹配. 某些鼠标可能 "精度过高" 以至于把任何抖动都传入系统了.
> 
> MAC版和Windows版比较手势的方式是一样的吗? 我刚刚试了一下, windows上有问题的鼠标, 在MAC版 BigSur 11.6 / WGesture 2.3.2 就没有任何问题. 正确触发率几乎100%, MAC版我设置的手势和Windows上是一模一样的.
> 
> windows之前我用 WGesture 1 也是几乎100%正确触发.

我最开始想到的就是重新录入手势, 前几天已经试过了, 刚刚也试了两个. 

而且我还发现一点, 我在同样的位置, 同样的角度画手势. 有4种情况: 
1. 触发了, 但是随着进一步滑动, 触发失败
2. 同样的角度, 完全没有触发
3. 轨迹刚开始出现一小段, 卡顿一下才出现剩下的轨迹. 这个时候鼠标已经移动了不少距离.
4. 开始没有出现轨迹, 结束时整条轨迹一起显示

电脑性能完全没有问题, i7-9750H 32G内存
![3](https://user-images.githubusercontent.com/65377438/137899456-e20dcad8-9452-46b1-801f-62b0237842fd.gif)

**Comment by luoshuaidev** [comment]
![4](https://user-images.githubusercontent.com/65377438/137933963-652f4f74-236f-40df-a001-41ae54cf5e62.gif)

@yingDev 找出一点规律了, 轮询率影响挺大. 

从1000改为500, 明显改善. (第一次测试估计是我DPI和轮询率一起改了, 没发现)
改为500, 能看到轨迹, 1000的时候, 就看不到轨迹了(或者只有一点点). 

不过这个鼠标只有两档, 500/1000, 没法判断更低是不是更好.

**Comment by zhj9709** [comment]
> ![4](https://user-images.githubusercontent.com/65377438/137933963-652f4f74-236f-40df-a001-41ae54cf5e62.gif)
> 
> @yingDev 找出一点规律了, 轮询率影响挺大.
> 
> 从1000改为500, 明显改善. (第一次测试估计是我DPI和轮询率一起改了, 没发现) 改为500, 能看到轨迹, 1000的时候, 就看不到轨迹了(或者只有一点点).
> 
> 不过这个鼠标只有两档, 500/1000, 没法判断更低是不是更好.

@yingDev 我罗技有125 250 500 1000 四档回报率，应该就是这里说的轮询率，设置成1000时手势轨迹就会延迟，2.5.0版本，之前版本不会，设置成其他三档就没什么问题

**Comment by yingDev** [comment]
@luoshuaidev  @zhj9709 
👍  等我鼠标到了应该很快能解决

**Comment by luoshuaidev** [comment]
> @luoshuaidev @zhj9709 👍 等我鼠标到了应该很快能解决

感谢, 这个软件大幅提高了电脑的使用体验和工作效率.

**Comment by yingDev** [comment]
@luoshuaidev @zhj9709 
很遗憾, 我买了这个鼠标, 问题却没有重现... 必定存在某些其它因素.



![image](https://user-images.githubusercontent.com/1680733/138444738-c8ddcc32-27de-4f83-8daa-43675d0273ec.png)



https://user-images.githubusercontent.com/1680733/138445334-dd164097-5064-43ca-807a-77a198d8eebe.mp4

**Comment by luoshuaidev** [comment]
> @luoshuaidev @zhj9709 很遗憾, 我买了这个鼠标, 问题却没有重现... 必定存在某些其它因素.
> 
> ![image](https://user-images.githubusercontent.com/1680733/138444738-c8ddcc32-27de-4f83-8daa-43675d0273ec.png)
> 
>  QQ.20211022190245_20211022191925.mp4

感谢大佬.

**Comment by yingDev** [comment]
很遗憾, 我买了这个鼠标, 问题却没有重现... 必定存在某些其它因素.

**Comment by luoshuaidev** [comment]
> 很遗憾, 我买了这个鼠标, 问题却没有重现... 必定存在某些其它因素.

我刚刚尝试了更改系统鼠标设置, 发现了明显改善的方法. 

![image](https://user-images.githubusercontent.com/65377438/138446949-b90a1eab-97e4-432c-ae87-5e7d1c994787.png)

修改这个指针移动速度, 之前比图上这个高不少, 大概在70%的位置. 现在降到40%左右, 鼠标轨迹明显变平滑, 触发正确率很接近之前了. 

![5](https://user-images.githubusercontent.com/65377438/138447628-f8c27808-6b0e-482f-91e7-158aad01101e.gif)

**Comment by yingDev** [comment]
@luoshuaidev  
👍
果然, 测试重现了!
这个 bug = 某些鼠标 + 系统指针速度

**Comment by zhj9709** [comment]
> @luoshuaidev 👍 果然, 测试重现了! 这个 bug = 某些鼠标 + 系统指针速度

系统指针设置默认，我的是跟鼠标回报率有关
![image](https://user-images.githubusercontent.com/13991774/138449161-3693ca82-0c3a-4467-b675-52bbcc62b22c.png)

125用着没啥问题，1000就是我视频中的样子，250,500好像也没啥问题
不同DPI没影响

**Comment by yingDev** [comment]
是否都没有勾选:
- [x] 提高指针精确度 ?

**Comment by zhj9709** [comment]
> 是否都没有勾选:
> 
> * [ ]  提高指针精确度 ?

没勾选

**Comment by yingDev** [comment]
@zhj9709 @luoshuaidev 
感谢你们的帮助.
我大致找到了识别不准的原因. 
- 鼠标抖动过度, 导致 WG 认为画出的手势与默认手势 ( 比如 ↙ 仅由 2 个点定义 ) 相差过大, 一票否决了.

下个版本应该会改善这种情况. 
目前缓解策略:

1) 降低指针速度, 降低轮询率 (可以理解为抖动敏感度)
2) 勾选 `✔ 提高指针精确度`, 系统会应用防抖算法.
3) 换个鼠标

轨迹延迟的问题应该也能解决.

**Comment by yingDev** [comment]
@zhj9709 @luoshuaidev 
试试这个初步修改版, 看是否有所改善?
 https://raw.githubusercontent.com/yingDev/WGestures2-bugs/main/res/Install%20WG2%20x64%202.5.1.msi

**Comment by zhj9709** [comment]
> @zhj9709 @luoshuaidev 试试这个初步修改版, 看是否有所改善? https://raw.githubusercontent.com/yingDev/WGestures2-bugs/main/res/Install%20WG2%20x64%202.5.1.msi

回报率设置成1000还是有问题

**Comment by yingDev** [comment]
> 
> 
> > @zhj9709 @luoshuaidev 试试这个初步修改版, 看是否有所改善? https://raw.githubusercontent.com/yingDev/WGestures2-bugs/main/res/Install%20WG2%20x64%202.5.1.msi
> 
> 回报率设置成1000还是有问题

具体表现如何?

**Comment by zhj9709** [comment]
> > > @zhj9709 @luoshuaidev 试试这个初步修改版, 看是否有所改善? https://raw.githubusercontent.com/yingDev/WGestures2-bugs/main/res/Install%20WG2%20x64%202.5.1.msi
> > 
> > 
> > 回报率设置成1000还是有问题
> 
> 具体表现如何?

跟我之前视频中的差不多，不过好像感觉好了一点点

**Comment by yingDev** [comment]
> 
> 
> > > > @zhj9709 @luoshuaidev 试试这个初步修改版, 看是否有所改善? https://raw.githubusercontent.com/yingDev/WGestures2-bugs/main/res/Install%20WG2%20x64%202.5.1.msi
> > > 
> > > 
> > > 回报率设置成1000还是有问题
> > 
> > 
> > 具体表现如何?
> 
> 跟我之前视频中的差不多，不过好像感觉好了一点点

# 明确一下:
## @zhj9709  反映的是 "轨迹延迟" 问题. 
  - 是 AMD 核显对吗?
  - 降低分辨率有改善么?

## @luoshuaidev  反映的是 "无法识别" 问题.
  - 测试版本是否有了明显改善?

**Comment by luoshuaidev** [comment]
> @zhj9709 @luoshuaidev 试试这个初步修改版, 看是否有所改善? https://raw.githubusercontent.com/yingDev/WGestures2-bugs/main/res/Install%20WG2%20x64%202.5.1.msi

我这边使用这个版本的情况如下: 
回报率500, 系统设置指针偏快: 
- 轨迹正常
- 触发正确
- 不会误触发

回报率1000, 系统设置指针(快慢结果相同): 
- 轨迹无改善
- 触发有改善
- 不会误触发 (之前横向滑动可能触发斜向滑动)

**Comment by zhj9709** [comment]
> > > > > @zhj9709 @luoshuaidev 试试这个初步修改版, 看是否有所改善? https://raw.githubusercontent.com/yingDev/WGestures2-bugs/main/res/Install%20WG2%20x64%202.5.1.msi
> > > > 
> > > > 
> > > > 回报率设置成1000还是有问题
> > > 
> > > 
> > > 具体表现如何?
> > 
> > 
> > 跟我之前视频中的差不多，不过好像感觉好了一点点
> 
> # 明确一下:
> ## @zhj9709 反映的是 "轨迹延迟" 问题.
> * 是 AMD 核显对吗?
> * 降低分辨率有改善么?
> 
> ## @luoshuaidev 反映的是 "无法识别" 问题.
> * 测试版本是否有了明显改善?

AMD核显。
降低分辨率没多大改善。
只有1000回报率会有问题。

**Comment by yingDev** [comment]
> 
> 
> > @luoshuaidev 👍 果然, 测试重现了! 这个 bug = 某些鼠标 + 系统指针速度
> 
> 系统指针设置默认，我的是跟鼠标回报率有关
> 
> 125用着没啥问题，1000就是我视频中的样子，250,500好像也没啥问题 不同DPI没影响

@zhj9709 鼠标型号和配置软件分别是?

**Comment by zhj9709** [comment]
> > > @luoshuaidev 👍 果然, 测试重现了! 这个 bug = 某些鼠标 + 系统指针速度
> > 
> > 
> > 系统指针设置默认，我的是跟鼠标回报率有关
> > 125用着没啥问题，1000就是我视频中的样子，250,500好像也没啥问题 不同DPI没影响
> 
> @zhj9709 鼠标型号和配置软件分别是?

有线：罗技G102
无线：罗技G304
两款设置都一样，用的软件也一样，Logitech G HUB，**我猜测罗技其他款鼠标回报率设置成1000时可能也有同样的问题**
台式机：R5 4650G
笔记本：R5 5600U
都是核显，系统版本都是Win11 Beta最新版。

测试了，回报率1000时，就会有轨迹延迟的情况，两台电脑，两个鼠标，都是这种情况。
2.5.0版本之前，我回报率也是1000， 但没有遇到这种情况。

**Comment by luoshuaidev** [comment]
> > @zhj9709 @luoshuaidev 试试这个初步修改版, 看是否有所改善? https://raw.githubusercontent.com/yingDev/WGestures2-bugs/main/res/Install%20WG2%20x64%202.5.1.msi
> 
> 我这边使用这个版本的情况如下: 回报率500, 系统设置指针偏快:
> 
> * 轨迹正常
> * 触发正确
> * 不会误触发
> 
> 回报率1000, 系统设置指针(快慢结果相同):
> 
> * 轨迹无改善
> * 触发有改善
> * 不会误触发 (之前横向滑动可能触发斜向滑动)

@yingDev 我又退回了网站的2.5.1比较了下, github版的2.5.1比网站2.5.1改善最明显的是手势识别正确率. 
github版使用除了轨迹显示问题, 其他都很好.

轨迹显示方面, 我这里最主要的影响因素也是回报率

**Comment by yingDev** [comment]
@zhj9709 @luoshuaidev 
好的, 谢谢!
我刚买这个雷蛇, 轮询率设为 1000 没有出现卡顿. (我怀疑这个 1000 是假的... 可能实际达不到, 所以没能引起延迟)
这个配置软件只支持 G 系列, 可能我还得买个鼠标 😂

**Comment by zhj9709** [comment]
> @zhj9709 @luoshuaidev 好的, 谢谢! 我刚买这个雷蛇, 轮询率设为 1000 没有出现卡顿. (我怀疑这个 1000 是假的... 可能实际达不到, 所以没能引起延迟) 这个配置软件只支持 G 系列, 可能我还得买个鼠标 😂

2.5.0改了什么吗，之前也没这个问题啊

**Comment by luoshuaidev** [comment]
![6](https://user-images.githubusercontent.com/65377438/138466751-80f0f0b1-935f-499e-99fb-91ea435853db.gif)
@yingDev 我再补充一点, 上图是1000和500的回报率的区别: 
1000的时候, 鼠标移动, 轨迹跟不上, 一旦鼠标停下来(触发键不松开), 之前的轨迹会全部显示出来. 
500的时候轨迹会跟随鼠标. 

1000的回报率, 除非我慢慢的移动鼠标, 这样轨迹也正常. 和DPI无关, 是手移动的速度, 非光标.  
正常操作的情况下, 我移动鼠标划轨迹速度都很快, github版虽然看不到轨迹, 但是正确触发了.

**Comment by luoshuaidev** [comment]
![7](https://user-images.githubusercontent.com/65377438/138468672-701de8c2-9ab3-432f-91c9-d3273b7ef01c.gif)

这是我这边2.4.4的状态.
1000 和 500 轨迹都能跟随, 
但是这个版本很容易出现误触发和没触发.

**Comment by yingDev** [comment]
@luoshuaidev @zhj9709 
请试试这个, 看是否改善了 延迟问题?
https://github.com/yingDev/WGestures2-bugs/blob/main/res/Install%20WG2%20x64%202.5.1%20a.msi?raw=true

**Comment by zhj9709** [comment]
> @luoshuaidev @zhj9709 请试试这个, 看是否改善了 延迟问题? https://github.com/yingDev/WGestures2-bugs/blob/main/res/Install%20WG2%20x64%202.5.1%20a.msi?raw=true

没问题了

**Comment by luoshuaidev** [comment]
> @luoshuaidev @zhj9709 请试试这个, 看是否改善了 延迟问题? https://github.com/yingDev/WGestures2-bugs/blob/main/res/Install%20WG2%20x64%202.5.1%20a.msi?raw=true

我这里也完全没问题了.

**Comment by yingDev** [comment]
2.5.2 已解决.
感谢各位的帮助 !
