### ISSUE TITLE
多显示器时左侧显示器触发右下右上时会同时触发为右侧显示器的左上左下指令

### ISSUE THREAD

**Issue by fzls** [yingDev/WGestures2-mac-bugs#56]
版本：windows版本
情况：连接多个显示器时，1.8.4版本中触发屏幕右上角和右下角可以正确识别，而2.5.1版本中除了触发右上和右下，还会同时触发为右侧显示器的左上角和左下角的对应指令。对比时感觉1.8.4版本似乎会在这种情况稍微阻止鼠标走到右侧，而2.5.1没有这个特殊处理

**Comment by fzls** [comment]
这是我的四个角的配置
![Snipaste_2021-10-20_09-46-06](https://user-images.githubusercontent.com/13483212/138014564-5bfbbaef-6c44-4d9c-b814-bb343a3b03a9.png)

**Comment by fzls** [comment]
当我触发右下角时（名称为显示桌面），此时会同时触发右侧显示器的左下角，导致 （开始） 的 Win 快捷键也被同时触发
![Snipaste_2021-10-20_09-49-24](https://user-images.githubusercontent.com/13483212/138014589-be945204-a460-4ace-8ec2-1f6f1b2bff9f.png)

**Comment by yingDev** [comment]
2.5.3 已解决
