### ISSUE TITLE
在clover中执行无效 

### ISSUE THREAD

**Issue by cclume** [yingDev/WGestures2-mac-bugs#59]
如题，请问这是因为？clover是一个文件夹管理软件。

**Comment by yingDev** [comment]
Clover 我倒是知道, 早在 WG 远古时期就有人反映过这个问题.

我测试了下, 好像没发现什么问题 (WG 2.5.3 + Win11)

能否详尽描述具体步骤和现象?

**Comment by yingDev** [comment]
顺便说一下, 我发现 clover 已经变成了广告软件, 不知道有没有其它流氓行为. 个人建议还是不要安装了.
![image](https://user-images.githubusercontent.com/1680733/138677181-9070381c-12f7-48af-9d64-238fbfe0c86d.png)
