### ISSUE TITLE
大键盘数字键作为修饰键无效，小键盘数字键正常

### ISSUE THREAD

**Issue by JohnKhanJr** [yingDev/WGestures2-mac-bugs#61]
如题，在手势录制界面中可以识别，但实际施放时无效

**Comment by yingDev** [comment]
我试了下, 好像能识别啊? 详细情况?

**Comment by JohnKhanJr** [comment]
> 我试了下, 好像能识别啊? 详细情况?

仔细排查了一下，是autohotkey引起的。想来是这样，昨天遇到两个问题，其一如标题，其二是屏幕角手势成功率过低的问题，可能是在排除第二个问题时关闭过autohotkey，问题仍然存在，却由于粗心大意，将之安到问题一上了。

**Comment by yingDev** [comment]
> 
> 
> > 我试了下, 好像能识别啊? 详细情况?
> 
> 仔细排查了一下，是autohotkey引起的。想来是这样，昨天遇到两个问题，其一如标题，其二是屏幕角手势成功率过低的问题，可能是在排除第二个问题时关闭过autohotkey，问题仍然存在，却由于粗心大意，将之安到问题一上了。

所以, 边角识别率的问题 2.5.4 是否有改善?

**Comment by JohnKhanJr** [comment]
> > > 我试了下, 好像能识别啊? 详细情况?
> > 
> > 
> > 仔细排查了一下，是autohotkey引起的。想来是这样，昨天遇到两个问题，其一如标题，其二是屏幕角手势成功率过低的问题，可能是在排除第二个问题时关闭过autohotkey，问题仍然存在，却由于粗心大意，将之安到问题一上了。
> 
> 所以, 边角识别率的问题 2.5.4 是否有改善?

识别率问题新版本已经修复了
