### ISSUE TITLE
2.6的优先级过高，导致其他软件定义的快捷键无效

### ISSUE THREAD

**Issue by JohnKhanJr** [yingDev/WGestures2-mac-bugs#65]
比如，通过autohotkey定义了一套x1+大键盘数字1、2、3、4、5为6、7、8、9、0，在旧版本（WG1、WG2.5）中只要保证相应的ahk脚本在WG2之后启动，就能生效。
但更新到2.6以后就不行了。

另外，动作：Lua脚本下方的API：WG示例对话框中“获得/设置简贴板文字或对象”，简应当是剪的同音别字？

**Comment by yingDev** [comment]
2.6.1 已解决
