### ISSUE TITLE
手势功能会自己失效，要暂停再开始才能再用

### ISSUE THREAD

**Issue by ThranduilL** [yingDev/WGestures2-mac-bugs#68]

**Comment by yingDev** [comment]
当出现失效的时候, 请将此日志文件发给我好么? `me@yingdev.com`
资源管理器地址栏输入:
`%appdata%\WGestures2\log.txt`

**Comment by ThranduilL** [comment]
> 当出现失效的时候, 请将此日志文件发给我好么? `me@yingdev.com` 资源管理器地址栏输入: `%appdata%\WGestures2\log.txt`

问题暂时解决了，是暂停快捷键被占用的问题，感谢您的回复，应用很好用。
