### ISSUE TITLE
win不能用手势快捷键锁屏

### ISSUE THREAD

**Issue by QQQOrange** [yingDev/WGestures2-mac-bugs#79]
用手势代替 win+l ，不能锁屏

**Comment by superDMS** [comment]
是的  这个我也尝试过  无法锁屏  反而会多打出个l键

**Comment by yingDev** [comment]
重复 https://github.com/yingDev/WGestures2-bugs/issues/46
cmd:
```cmd
rundll32.exe user32.dll,LockWorkStation
```

下个版本考虑特殊处理 Win+L, 和 WG1 一样.

**Comment by yingDev** [comment]
2.7.1 已解决
