### ISSUE TITLE
运行/激活程序功能bug.

### ISSUE THREAD

**Issue by superDMS** [yingDev/WGestures2-mac-bugs#81]
程序窗口最大化状态下点最小化之后,再次使用激活程序命令,则窗口自动取消最大化..测试过多个程序都是这样.  程序窗口(如浏览器)最小化之前是最大化状态的,   激活唤醒之后择自动取消窗口最大化, 老是得重新去点窗口最大化,,,,,正常逻辑应该是照旧还原后台窗口后台之前的样子即可. 自动取消最大化应为bug.

**Comment by yingDev** [comment]
2.7.1 已解决
