### ISSUE TITLE
【BUG反馈】2.6.1升级安装到2.7.0时程序崩溃

### ISSUE THREAD

**Issue by TwentyCat** [yingDev/WGestures2-mac-bugs#84]
环境：Win10 20H2 19042.867、安装了ESET NOD32杀毒软件、系统还原开启
复现方法：
1、卸载WGestures
2、安装WGestures 2.6.1版
3、重启
4、安装WGestures 2.7.0版
5、此时会弹窗提示程序异常，此后程序再也打不开，如图所示

![1](https://user-images.githubusercontent.com/29301103/142746363-dbfdd9cc-20eb-48f9-8d43-2861cac77d3d.png)

解决方法：
卸载WGestures 2.6.1，并全新安装WGestures 2.7.0版，此时问题解决。

附以上安装包：
https://drive.google.com/file/d/1RNPbFY2RBwRMPwF-74lKEake5WkWK3Pr/view?usp=sharing

特此反馈。

**Comment by Qee2** [comment]
我安装2.7.0版本时，把2.6版本的软件退出来了，然后再执行安装。但是新版本程序再也打不开了。我卸载重新安装试试。

**Comment by Qee2** [comment]
卸载再重新安装新版本，程序终于可以正常使用了。谢谢大大。

**Comment by JohnKhanJr** [comment]
不用卸载，再次运行2.7.0安装程序，选[修复]项，可以成功安装并运行

**Comment by yingDev** [comment]
2.7.1 已解决
