### ISSUE TITLE
Lua脚本的日志默认无法显示

### ISSUE THREAD

**Issue by JohnKhanJr** [yingDev/WGestures2-mac-bugs#88]
需要先打开WG或示例脚本窗口，方才会在该窗口末尾追加日志，
换句话说，日志只能夺舍其它窗口

**Comment by yingDev** [comment]
日志窗口主要用於編寫代碼時調試

并不是用於 "顯示執行結果" 之類.

因此, 關閉狀態下不會記錄任何信息, 以減少開銷.
