### ISSUE TITLE
触发手势后,有时候进错了手势分支,未匹配命令的情况希望拦截掉右键(手势触发键)

### ISSUE THREAD

**Issue by superDMS** [yingDev/WGestures2-mac-bugs#93]
触发手势后,有时候进错了手势分支,任意点几个键取消施法后希望拦截掉右键(手势触发键),
比如我点了右键(手势触发键)+a  但点成了+s,,,常规就是瞎点几个键让手势无匹配,  然后再重新触发,,  然而未匹配到命令能取消本次手势,,但右键(手势触发键)依然被触发了  ,只要没有匹配到手势命令就会触发原手势键,,,,但日常使用来讲  没匹配到手势键100%是因为进错了分支导致想重新开始手势.,所以只要非单点右键(手势触发键)未匹配命令就可以视为取消,重新开始手势,所以可以屏蔽掉此次触发的右键(手势触发键)功能.

**Comment by yingDev** [comment]
? 好像并不是这样的行为呀? 

正常情况下, 不匹配就会变为未识别, 就不会执行任何操作.

有没有视频?

**Comment by superDMS** [comment]
> ? 好像并不是这样的行为呀?
> 
> 正常情况下, 不匹配就会变为未识别, 就不会执行任何操作.
> 
> 有没有视频?

比如在桌面,浏览器里,,,右键+xxx(任意输入使其未匹配)  ,然后放开右键,,,,,,右键菜单就出来了,,右键并未被拦截.........

**Comment by superDMS** [comment]
> ...

忘记说明:特指不画线的情况下!!    ,,,,画线会拦截,,,,刚刚试过!  不画线 直接输入字母则会弹出!

**Comment by yingDev** [comment]
哦, 明白了

**Comment by yingDev** [comment]
2.8已修复
