### ISSUE TITLE
“执行时不显示手势名称”这个设置和“识别手势时立即执行”这个设置 双重bug

### ISSUE THREAD

**Issue by yangyzp** [yingDev/WGestures2-mac-bugs#98]
bug1：“执行时不显示手势名称”这个设置必须和“识别手势时立即执行”这个设置一起勾选才有效。
bug2：“执行时不显示手势名称”这个设置无法保存，当再次点击手势设置时，“执行时不显示手势名称”这个设置的勾就会自动被取消，然后下次执行手势的时候，名称又自动显示了。

下面是bug录制的视频：
链接: https://pan.baidu.com/s/1Kx_WMiVJ7QVmB36K7zoW9w 提取码: shkr

**Comment by yangyzp** [comment]
另外，希望保留 1代的黑名单功能，比如在游戏的时候，不希望全局下面的手势起作用。这个蛮重要

**Comment by yingDev** [comment]
即将发布的 2.8 已修复.
另外, 添加应用程序, 然后禁用所有触发方式, 就等于黑名单.
